services:
  product-db:
    image: postgres:15.2
    container_name: product-db
    restart: always
    env_file:
      - ./env/product-db.env
    ports:
      - 5433:5432
    networks:
      - sales-network
  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - '6379:6379'
    networks:
      - sales-network
    volumes: 
      - cache:/data
  product-api:
    build:
      context: './product-api'
      dockerfile: '.dev/dev.Dockerfile'
    container_name: product_api
    env_file:
      - ./env/product.env
    ports:
      - 8081:8080
    depends_on:
      - product-db
      - sales-rabbit
      - cache
    networks:
      - sales-network

volumes:
  cache:
    driver: local
