services:
  product-db:
    image: postgres:15.2
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432
    networks:
      - sales-network
  product-api:
    build:
      context: './product-api'
      dockerfile: '.dev/dev.Dockerfile'
    container_name: product_api
    env_file:
      - ./env/product.env
    ports:
      - 8081:8080
    depends_on:
      - product-db
      - sales-rabbit
    networks:
      - sales-network
