server:
  port: 8080

api:
  name: product-api
  version: '1.0.0'
  v1:
    name: 'v1'
    endpoint-prefix: 'v1'

spring:
  application:
    name: '${api.name}'
  liquibase:
    change-log: db/changelog/master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql
  jpa:
    database: default
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        generate_statistics: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USER}
    password: ${RABBIT_MQ_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

app-config:
  rabbit:
    exchange:
      product: product.topic
    queue:
      product-stock: product-stock-update.queue
      sales-confirmation: sales-confirmation.queue
    routingKey:
      product-stock: product-stock-update.routingKey
      sales-confirmation: sales-confirmation.routingKey

datasource:
  product:
    driverClassName: 'org.postgresql.Driver'
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    liquibase:
      changelog: 'db/changelog/master.yaml'