server:
  port: 8081

api:
  name: product-api
  version: '1.0.0'
  v1:
    name: 'v1'
    endpoint-prefix: 'v1'

spring:
  application:
    name: '${api.name}'
  liquibase:
    change-log:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:product-db}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:123456}
    initialize: true
    maxActive: 3
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql
  jpa:
    database: default
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        generate_statistics: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
    virtual-host: ${RABBIT_MQ_VHOST:}

app-config:
  rabbit:
    exchange:
      product: product.topic
    queue:
      product-stock: product-stock-update.queue
      sales-confirmation: sales-confirmation.queue
    routingKey:
      product-stock: product-stock-update.routingKey
      sales-confirmation: sales-confirmation.routingKey

datasource:
  product:
    driverClassName: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5432/product-db'
    username: 'admin'
    password: '123456'
    liquibase:
      changelog: 'db/changelog/master.yaml'