spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: h2
  liquibase:
    url: jdbc:h2:mem:product-db
    user: sa
    password:

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

datasource:
  driver-class-name: 'org.hsqldb.jdbc.JDBCDriver'
  url: jdbc:h2:mem:product-db
  user: sa
  password:
